# docker-compose --compatibility up -d
version: "3.4"

services:
  app:
    image: docker.io/roandocker/ivc-gateway:v1.0.0
    container_name: ivc-gateway
    ports:
      - 8800:8800
      - 8801:8801
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 1g
        reservations:
          cpus: '2'
          memory: 1g
    volumes:
    - ./config:/opt/app/config

      