# runtime setting
# default run mode
RUN_MODE: 'dev'
# http server debug mode (debug、release、test)
HTTP_DEBUG_MODE: 'debug'
# HTTP Req Timeout
HTTP_TIME_DURATION: 10
# page size
PAGE_SIZE: 20
# server port
HTTP_SERVER_PORT: '9800'
# gRPC port
GRPC_PORT: '8800'


# db setting
# default db host
DB_HOST: '172.16.40.8'
# db driver (support mysql, postgresql, sqlite, sql server)
DB_DRIVER: 'mysql' 
# default db port
DB_PORT: '3306'
# default db name
DB_NAME: 'zhuiyi'
# db user
DB_USER: 'root'
# db password
DB_PASSWD: 'uWXf87plmQGz8zMM'
# db max idle conns
DB_MAX_IDLE_CONNS: 10
# db max open conns
DB_MAX_OPEN_CONNS: 100
# db conn max life time (minutes)
DB_CONN_MAX_LIFETIME: 60
# slow sql
DB_SLOWTHRESHOLD: 5
# db log (silent, error, warn, info)
DB_LOGMODE: 'info'


# cache setting
# cache enable
CACHE_ENABLED: false
# cache connect mode (cluster, single)
CACHE_CONNECT_MODE: 'single'
# cache address
CACHE_ADDRESS: '127.0.0.1:30379'
# cache passwd
CACHE_PASSWD: 'zhuiyi123'
# cache pool size
CACHE_POOL_SIZE: 15
# cache minidle conns
CACHE_MINIDLE_CONNS: 10
# cache db
CACHE_DB: 0


# log setting
# log Level （info、debug、error）
LOG_LEVEL: 'info'
# log max age (minutes, default 30 days)
LOG_MAX_AGE: 43200
# log rotation time (minutes, default 1 days)
LOG_ROTATION_TIME: 1140



