apiVersion: v1
kind: ServiceAccount
metadata:
  name: zhuiyisa
  namespace: zhuiyi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: zhuiyi
  name: zhuiyirb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zhuiyirole
subjects:
- kind: ServiceAccount
  name: default